### ISSUE TITLE
Import library

### ISSUE THREAD

**Issue by YahyaL** [as-ideas/headliner#11]
Hi,

Thank you so much for sharing this library. It seems to be very easy to use compared to others.

I try to import the library to reproduce your example but I receive an error message : 

 File "/home/ubuntu/.local/lib/python3.5/site-packages/headliner/model/summarizer.py", line 14
    self.vectorizer: Union[Vectorizer, None] = None
                         ^
SyntaxError: invalid syntax

I am running Python 3.5.2.

Am I doing something wrong?

Thanks

**Comment by cschaefer26** [comment]
Hi, the lib is compatible with Python >=3.6, would it be possible for you to upgrade to Python 3.6?

**Comment by YahyaL** [comment]
Thanks for your quick reply
