### ISSUE TITLE
Colab hosted notebooks for quick demo.

### ISSUE THREAD

**Issue by sainimohit23** [as-ideas/headliner#12]
It is not an issue. It is more like a suggestion. 

Is it possible to have google colab hosted notebooks like [this](https://drive.google.com/open?id=18w5tMYT1BWTanN8DfYZZrXQrgHYmkd1o) in the documentation to play around with code and to run quick demos?

**Comment by cschaefer26** [comment]
Hi, we have two tutorials in the docs, one of them: https://as-ideas.github.io/headliner/examples/advanced_nmt_example/

Best, Chris
